version: '3.9'

services:
  app:
    container_name: app
    hostname: app
    build: ./app
    env_file: .env
    entrypoint: uvicorn main:app --host 0.0.0.0 --reload --port ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./app:/home/user/app
    restart: always

  rabbitmq:
    container_name: rabbitmq
    hostname: ${RABBITMQ_HOSTNAME}
    image: rabbitmq:3.8
    volumes:
      - ./rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq
    restart: always

  redis:
    container_name: redis
    hostname: ${REDIS_HOSTNAME}
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    restart: always

  worker:
    container_name: worker
    hostname: worker
    build: ./worker
    env_file: .env
    command: watchmedo auto-restart -- celery -c ${CELERY_NUM_WORKERS} worker -l info -A celery_app.celery_app
    volumes:
      - ./worker:/home/user/worker
    depends_on:
      - rabbitmq
      - redis
    restart: always

  monitor:
    container_name: monitor
    build: ./worker
    env_file: .env
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    entrypoint: flower
    command: -A celery_app.celery_app --port=$FLOWER_PORT --broker=amqp://$RABBITMQ_USERNAME:$RABBITMQ_PASSWORD@$RABBITMQ_HOSTNAME:$RABBITMQ_NODE_PORT_NUMBER//
    depends_on:
      - redis
      - rabbitmq
    restart: always

volumes:
  redis-data:
  rabbitmq-data:
  rabbitmq-logs: