version: '3.9'

services:
  app:
    container_name: app
    hostname: app
    build: ./app
    env_file: .env
    entrypoint: uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    restart: always

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/
      - ./rabbitmq/log:/var/log/rabbitmq
    restart: always

  redis:
    container_name: redis
    hostname: redis
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
    restart: always

  worker:
    container_name: worker
    hostname: worker
    build: ./worker
    env_file: .env
    depends_on:
      - rabbitmq
      - redis
    restart: always

  monitor:
    build: ./worker
    ports:
      - 5555:5555
    entrypoint: flower
    env_file: .env
    command:  -A tasks --port=5555 --broker=amqp://$RABBITMQ_USERNAME:$RABBITMQ_PASSWORD@rabbitmq:$RABBITMQ_NODE_PORT_NUMBER//
    depends_on:
      - redis