version: '3.9'

services:
  app:
    container_name: app
    hostname: app
    build: ./app
    env_file: .env
    entrypoint: uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    restart: always

  rabbitmq:
    container_name: rabbitmq
    hostname: ${RABBITMQ_HOSTNAME}
    image: rabbitmq:3.8
    volumes:
      - ./rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/
      - ./rabbitmq/log:/var/log/rabbitmq
    restart: always

  redis:
    container_name: redis
    hostname: ${REDIS_HOSTNAME}
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/data:/data
    restart: always

  worker-prod:
    container_name: worker
    hostname: worker
    build: 
      context: ./worker
      dockerfile: dockerfile.prod
    env_file: .env
    command: celery worker -c ${CELERY_NUM_WORKERS} -A celery_app.celery_app --loglevel=info --logfile=./logs/celery.log
    depends_on:
      - rabbitmq
      - redis
    restart: always

  monitor:
    container_name: monitor
    build: 
      context: ./worker
      dockerfile: dockerfile.prod
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    entrypoint: flower
    env_file: .env
    command: -A celery_app.celery_app --port=$FLOWER_PORT --broker=amqp://$RABBITMQ_USERNAME:$RABBITMQ_PASSWORD@$RABBITMQ_HOSTNAME:$RABBITMQ_NODE_PORT_NUMBER//
    depends_on:
      - redis
      - rabbitmq
    restart: always
    