version: '3.9'

services:
  app:
    container_name: app
    hostname: app
    build: ./app
    entrypoint: uvicorn main:app --host 0.0.0.0 --reload --port ${BACKEND_PORT}
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: bitnami/rabbitmq:3.8
    env_file: .env
    volumes:
      - 'rabbitmq-data:/bitnami'
    restart: always

  redis:
    container_name: redis
    image: bitnami/redis:6.2
    env_file: .env
    volumes:
      - redis-data:/data
    restart: always

  worker:
    container_name: worker
    hostname: worker
    build: ./worker
    env_file: .env
    depends_on:
      - rabbitmq
      - redis
    restart: always

volumes:
  redis-data:
  rabbitmq-data:
